### PR TITLE
lots of things, let me know what you think.

### PR DESCRIPTION
**Pull request by DakJaniels**
```
No LibSlashCommander :
```
no_lsc
```
With LibSlashCommander :
```
libslashcommander_intigration

### CODE REVIEW

**Comment by moshulu** [comment]
This is great stuff, @DakJaniels, I am so glad you took the time to tighten up SimpleClock.

I'm going to add all of the changes to the main branch and then update the Addon in ESOUI after some more features are integrated (which are still in the works on my end). 

A few quick questions, out of curiosity:

-  how did you translate everything so quickly?
- How did you get resources/esobindings.xsd?
- How did you generate resources/esoui101040.xsd? 
- I don't like including .vscode folders in commits, would you be opposed to leaving this out? I don't like pigeonholing people into using one IDE over another. How do you feel about that?

**Comment by DakJaniels** [comment]
> * how did you translate everything so quickly?
Ai is pretty good at translating language. https://cloud.google.com/vertex-ai/docs The new Vertex Ai from google is what I used for this addons language files. 
> * How did you get resources/esobindings.xsd?
https://sir.insidi.at/or/2018/07/10/schema-definition-for-esoui-xml/
> * How did you generate resources/esoui101040.xsd?
with https://github.com/sirinsidiator/esoui-doc-converter
> * I don't like including .vscode folders in commits, would you be opposed to leaving this out? I don't like pigeonholing people into using one IDE over another. How do you feel about that?
that's fine, it's more of a resource than anything. could also make a dev branch and have the tools there.

**Comment by moshulu** [comment]
Thanks for your response. I did some digging on how to use the XSD validator for ESO and how it works, and it's an awesome tool! I'm still learning how to develop ESO addons efficiently. I have done some videos on how to actually program them, and I'm going to include your edits and the tools that you've mentioned in next week's video.

Awesome work!

**Comment by moshulu** [comment]
I have changed the targeted branch to `dev`, as `main` will be specifically for releases for esoui.com.

**Comment by DakJaniels** [comment]
Awesome. @Baertram on esoui had some changes for the localization too https://www.esoui.com/forums/showthread.php?t=10767

**Pull request merged**
